name: movie_list_app
description: Top movies.

publish_to: 'none' 


version: 1.0.0+1


environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  get_it: ^7.6.0
  injectable: ^2.1.2
  drift: ^2.10.0
  dio: ^5.3.0
  dartz: ^0.10.1
  provider: ^6.0.5
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.15
  path: ^1.8.3
  sqlite3_flutter_libs: ^0.5.15
  cached_network_image: ^3.2.3

  
dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  drift_dev: ^2.10.0
  injectable_generator: ^2.0.0


flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/icon_app.png"


flutter:
  uses-material-design: true

  assets:
    - assets/icon/


  
  fonts:
    - family: TvMiniIcons
      fonts:
        - asset: assets/fonts/icons/TvMiniIcons.ttf
    - family: TTNormsPro
      fonts:
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Thin.ttf
          weight: 100        
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Light.ttf
          weight: 300
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Regular.ttf
          weight: 400 
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-Medium.ttf
          weight: 500 
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-ExtraBold.ttf
          weight: 700 
        - asset: assets/fonts/tt_norms_pro/TTNormsPro-ExtraBlack.ttf
          weight: 900 
    - family: Archivo
      fonts:
        - asset: assets/fonts/archivo/Archivo_Condensed-BlackItalic.ttf
          weight: 900 
