/// Flutter icons TvMiniIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TvMiniIcons
///      fonts:
///       - asset: fonts/TvMiniIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TvMiniIcons {
  TvMiniIcons._();

  static const _kFontFam = 'TvMiniIcons';
  static const String? _kFontPkg = null;

  static const IconData up_arrow = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData movies = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData television = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData favorite = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
